### ISSUE TITLE
Typescript error after updating to 1.3.0

### ISSUE THREAD

**Issue by ennetech** [vuetifyjs/vuetify#5393]
After updating from 1.2 to 1.3 my project stops building due to typescript errors, i cannot share my current project, but i am going to setup a repo with the reproduction

```
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
42:31 Property 'value' does not exist on type 'CombinedVueInstance<Vue, {}, {}, {}, Readonly<{ activeClass: string; mandatory: boolean; max: str...'.
    40 |       // Otherwise, check if multiple
    41 |       // to determine which default to provide
  > 42 |       internalLazyValue: this.value !== undefined
       |                               ^
    43 |         ? this.value
    44 |         : this.multiple ? [] : undefined,
    45 |       items: [] as GroupableInstance[]
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
43:16 Property 'value' does not exist on type 'CombinedVueInstance<Vue, {}, {}, {}, Readonly<{ activeClass: string; mandatory: boolean; max: str...'.
    41 |       // to determine which default to provide
    42 |       internalLazyValue: this.value !== undefined
  > 43 |         ? this.value
       |                ^
    44 |         : this.multiple ? [] : undefined,
    45 |       items: [] as GroupableInstance[]
    46 |     }
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
52:17 Property 'themeClasses' does not exist on type 'CombinedVueInstance<Vue, { internalLazyValue: any; items: GroupableInstance[]; }, { getValue(item...'.
    50 |     classes (): Record<string, boolean> {
    51 |       return {
  > 52 |         ...this.themeClasses
       |                 ^
    53 |       }
    54 |     },
    55 |     selectedItems (): GroupableInstance[] {
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
61:33 Property 'internalValue' does not exist on type 'CombinedVueInstance<Vue, { internalLazyValue: any; items: GroupableInstance[]; }, { getValue(item...'.
    59 |     },
    60 |     selectedValues (): any[] {
  > 61 |       return Array.isArray(this.internalValue)
       |                                 ^
    62 |         ? this.internalValue
    63 |         : [this.internalValue]
    64 |     },
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
62:16 Property 'internalValue' does not exist on type 'CombinedVueInstance<Vue, { internalLazyValue: any; items: GroupableInstance[]; }, { getValue(item...'.
    60 |     selectedValues (): any[] {
    61 |       return Array.isArray(this.internalValue)
  > 62 |         ? this.internalValue
       |                ^
    63 |         : [this.internalValue]
    64 |     },
    65 |     toggleMethod (): (v: any) => boolean {
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
63:17 Property 'internalValue' does not exist on type 'CombinedVueInstance<Vue, { internalLazyValue: any; items: GroupableInstance[]; }, { getValue(item...'.
    61 |       return Array.isArray(this.internalValue)
    62 |         ? this.internalValue
  > 63 |         : [this.internalValue]
       |                 ^
    64 |     },
    65 |     toggleMethod (): (v: any) => boolean {
    66 |       if (!this.multiple) {
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
67:33 Property 'internalValue' does not exist on type 'CombinedVueInstance<Vue, { internalLazyValue: any; items: GroupableInstance[]; }, { getValue(item...'.
    65 |     toggleMethod (): (v: any) => boolean {
    66 |       if (!this.multiple) {
  > 67 |         return (v: any) => this.internalValue === v
       |                                 ^
    68 |       }
    69 | 
    70 |       const internalValue = this.internalValue
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
70:34 Property 'internalValue' does not exist on type 'CombinedVueInstance<Vue, { internalLazyValue: any; items: GroupableInstance[]; }, { getValue(item...'.
    68 |       }
    69 | 
  > 70 |       const internalValue = this.internalValue
       |                                  ^
    71 |       if (Array.isArray(internalValue)) {
    72 |         return (v: any) => internalValue.includes(v)
    73 |       }
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
72:42 Property 'includes' does not exist on type 'any[]'.
    70 |       const internalValue = this.internalValue
    71 |       if (Array.isArray(internalValue)) {
  > 72 |         return (v: any) => internalValue.includes(v)
       |                                          ^
    73 |       }
    74 | 
    75 |       return () => false
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
84:46 Property 'internalValue' does not exist on type 'CombinedVueInstance<Vue, { internalLazyValue: any; items: GroupableInstance[]; }, { getValue(item...'.
    82 | 
    83 |   created () {
  > 84 |     if (this.multiple && !Array.isArray(this.internalValue)) {
       |                                              ^
    85 |       consoleWarn('Model must be bound to an array if the multiple property is true.', this)
    86 |     }
    87 |   },
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
94:52 Cannot find name 'unknown'.
    92 | 
    93 |   methods: {
  > 94 |     getValue (item: GroupableInstance, i: number): unknown {
       |                                                    ^
    95 |       return item.value == null || item.value === ''
    96 |         ? i
    97 |         : item.value
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
130:47 Property 'internalValue' does not exist on type 'CombinedVueInstance<Vue, { internalLazyValue: any; items: GroupableInstance[]; }, { getValue(item...'.
    128 | 
    129 |       // Remove the value
  > 130 |       if (this.multiple && Array.isArray(this.internalValue)) {
        |                                               ^
    131 |         this.internalValue = this.internalValue.filter(v => v !== value)
    132 |       } else {
    133 |         this.internalValue = undefined
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
131:14 Property 'internalValue' does not exist on type 'CombinedVueInstance<Vue, { internalLazyValue: any; items: GroupableInstance[]; }, { getValue(item...'.
    129 |       // Remove the value
    130 |       if (this.multiple && Array.isArray(this.internalValue)) {
  > 131 |         this.internalValue = this.internalValue.filter(v => v !== value)
        |              ^
    132 |       } else {
    133 |         this.internalValue = undefined
    134 |       }
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
131:35 Property 'internalValue' does not exist on type 'CombinedVueInstance<Vue, { internalLazyValue: any; items: GroupableInstance[]; }, { getValue(item...'.
    129 |       // Remove the value
    130 |       if (this.multiple && Array.isArray(this.internalValue)) {
  > 131 |         this.internalValue = this.internalValue.filter(v => v !== value)
        |                                   ^
    132 |       } else {
    133 |         this.internalValue = undefined
    134 |       }
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
131:56 Parameter 'v' implicitly has an 'any' type.
    129 |       // Remove the value
    130 |       if (this.multiple && Array.isArray(this.internalValue)) {
  > 131 |         this.internalValue = this.internalValue.filter(v => v !== value)
        |                                                        ^
    132 |       } else {
    133 |         this.internalValue = undefined
    134 |       }
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
133:14 Property 'internalValue' does not exist on type 'CombinedVueInstance<Vue, { internalLazyValue: any; items: GroupableInstance[]; }, { getValue(item...'.
    131 |         this.internalValue = this.internalValue.filter(v => v !== value)
    132 |       } else {
  > 133 |         this.internalValue = undefined
        |              ^
    134 |       }
    135 | 
    136 |       // If mandatory and we have no selection
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
175:47 Property 'internalValue' does not exist on type 'CombinedVueInstance<Vue, { internalLazyValue: any; items: GroupableInstance[]; }, { getValue(item...'.
    173 |     },
    174 |     updateMultiple (value: any) {
  > 175 |       const defaultValue = Array.isArray(this.internalValue)
        |                                               ^
    176 |         ? this.internalValue
    177 |         : []
    178 |       const internalValue = defaultValue.slice()
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
176:16 Property 'internalValue' does not exist on type 'CombinedVueInstance<Vue, { internalLazyValue: any; items: GroupableInstance[]; }, { getValue(item...'.
    174 |     updateMultiple (value: any) {
    175 |       const defaultValue = Array.isArray(this.internalValue)
  > 176 |         ? this.internalValue
        |                ^
    177 |         : []
    178 |       const internalValue = defaultValue.slice()
    179 |       const index = internalValue.findIndex(val => val === value)
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
179:45 Parameter 'val' implicitly has an 'any' type.
    177 |         : []
    178 |       const internalValue = defaultValue.slice()
  > 179 |       const index = internalValue.findIndex(val => val === value)
        |                                             ^
    180 | 
    181 |       if (
    182 |         this.mandatory &&
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
202:12 Property 'internalValue' does not exist on type 'CombinedVueInstance<Vue, { internalLazyValue: any; items: GroupableInstance[]; }, { getValue(item...'.
    200 |         : internalValue.push(value)
    201 | 
  > 202 |       this.internalValue = internalValue
        |            ^
    203 |     },
    204 |     updateSingle (value: any) {
    205 |       const isSame = value === this.internalValue
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
205:37 Property 'internalValue' does not exist on type 'CombinedVueInstance<Vue, { internalLazyValue: any; items: GroupableInstance[]; }, { getValue(item...'.
    203 |     },
    204 |     updateSingle (value: any) {
  > 205 |       const isSame = value === this.internalValue
        |                                     ^
    206 | 
    207 |       if (this.mandatory && isSame) return
    208 | 
ERROR in C:/projects/node_modules/vuetify/src/components/VItemGroup/VItemGroup.ts
209:12 Property 'internalValue' does not exist on type 'CombinedVueInstance<Vue, { internalLazyValue: any; items: GroupableInstance[]; }, { getValue(item...'.
    207 |       if (this.mandatory && isSame) return
    208 | 
  > 209 |       this.internalValue = isSame ? undefined : value
        |            ^
    210 |     }
    211 |   },
    212 | 
ERROR in C:/projects/node_modules/vuetify/src/components/VWindow/VWindow.ts
64:21 Property 'internalValue' does not exist on type 'CombinedVueInstance<{ internalLazyValue: any; items: GroupableInstance[]; } & { getValue(item: Gr...'.
    62 |     internalIndex (): number {
    63 |       return this.items.findIndex((item, i) => {
  > 64 |         return this.internalValue === this.getValue(item, i)
       |                     ^
    65 |       })
    66 |     },
    67 |     internalReverse (): boolean {
ERROR in C:/projects/node_modules/vuetify/src/components/VWindow/VWindow.ts
91:21 Property 'options' does not exist on type 'VueConstructor<{ internalLazyValue: any; items: GroupableInstance[]; } & { getValue(item: Groupab...'.
    89 |     },
    90 |     init () {
  > 91 |       BaseItemGroup.options.methods.init.call(this)
       |                     ^
    92 | 
    93 |       // Ensure no entry animation
    94 |       this.$nextTick(() => (this.isBooted = true))
ERROR in C:/projects/node_modules/vuetify/src/components/VWindow/VWindow.ts
101:12 Property 'internalValue' does not exist on type 'CombinedVueInstance<{ internalLazyValue: any; items: GroupableInstance[]; } & { getValue(item: Gr...'.
     99 |       const item = this.items[nextIndex]
    100 | 
  > 101 |       this.internalValue = this.getValue(item, nextIndex)
        |            ^
    102 |     },
    103 |     prev () {
    104 |       this.isReverse = true
ERROR in C:/projects/node_modules/vuetify/src/components/VWindow/VWindow.ts
108:12 Property 'internalValue' does not exist on type 'CombinedVueInstance<{ internalLazyValue: any; items: GroupableInstance[]; } & { getValue(item: Gr...'.
    106 |       const item = this.items[lastIndex]
    107 | 
  > 108 |       this.internalValue = this.getValue(item, lastIndex)
        |            ^
    109 |     },
    110 |     updateReverse (val: number, oldVal: number) {
    111 |       this.isReverse = val < oldVal
ERROR in C:/projects/node_modules/vuetify/src/components/VWindow/VWindowItem.ts
125:13 Property 'showLazyContent' does not exist on type 'CombinedVueInstance<options & Vue, { isActive: boolean; wasCancelled: boolean; }, { genDefaultSlo...'.
    123 |       }] as VNodeDirective[],
    124 |       on: this.$listeners
  > 125 |     }, this.showLazyContent(this.genDefaultSlot()))
        |             ^
    126 | 
    127 |     return h('transition', {
    128 |       props: {
ERROR in C:/projects/node_modules/vuetify/src/directives/touch.ts
119:10 Property '_touchHandlers' does not exist on type 'HTMLElement'.
    117 | 
    118 |   const handlers = createHandlers(binding.value)
  > 119 |   target._touchHandlers = Object(target._touchHandlers)
        |          ^
    120 |   target._touchHandlers![vnode.context!._uid] = handlers
    121 | 
    122 |   keys(handlers).forEach(eventName => {
ERROR in C:/projects/node_modules/vuetify/src/directives/touch.ts
119:41 Property '_touchHandlers' does not exist on type 'HTMLElement'.
    117 | 
    118 |   const handlers = createHandlers(binding.value)
  > 119 |   target._touchHandlers = Object(target._touchHandlers)
        |                                         ^
    120 |   target._touchHandlers![vnode.context!._uid] = handlers
    121 | 
    122 |   keys(handlers).forEach(eventName => {
ERROR in C:/projects/node_modules/vuetify/src/directives/touch.ts
120:10 Property '_touchHandlers' does not exist on type 'HTMLElement'.
    118 |   const handlers = createHandlers(binding.value)
    119 |   target._touchHandlers = Object(target._touchHandlers)
  > 120 |   target._touchHandlers![vnode.context!._uid] = handlers
        |          ^
    121 | 
    122 |   keys(handlers).forEach(eventName => {
    123 |     target.addEventListener(eventName, handlers[eventName] as EventListener, options)
ERROR in C:/projects/node_modules/vuetify/src/directives/touch.ts
120:41 Property '_uid' does not exist on type 'Vue'.
    118 |   const handlers = createHandlers(binding.value)
    119 |   target._touchHandlers = Object(target._touchHandlers)
  > 120 |   target._touchHandlers![vnode.context!._uid] = handlers
        |                                         ^
    121 | 
    122 |   keys(handlers).forEach(eventName => {
    123 |     target.addEventListener(eventName, handlers[eventName] as EventListener, options)
ERROR in C:/projects/node_modules/vuetify/src/directives/touch.ts
129:26 Property '_touchHandlers' does not exist on type 'HTMLElement'.
    127 | function unbind (el: HTMLElement, binding: TouchVNodeDirective, vnode: VNode) {
    128 |   const target = binding.value.parent ? el.parentElement : el
  > 129 |   if (!target || !target._touchHandlers) return
        |                          ^
    130 | 
    131 |   const handlers = target._touchHandlers[vnode.context!._uid]
    132 |   keys(handlers).forEach(eventName => {
ERROR in C:/projects/node_modules/vuetify/src/directives/touch.ts
131:27 Property '_touchHandlers' does not exist on type 'HTMLElement'.
    129 |   if (!target || !target._touchHandlers) return
    130 | 
  > 131 |   const handlers = target._touchHandlers[vnode.context!._uid]
        |                           ^
    132 |   keys(handlers).forEach(eventName => {
    133 |     target.removeEventListener(eventName, handlers[eventName])
    134 |   })
ERROR in C:/projects/node_modules/vuetify/src/directives/touch.ts
131:57 Property '_uid' does not exist on type 'Vue'.
    129 |   if (!target || !target._touchHandlers) return
    130 | 
  > 131 |   const handlers = target._touchHandlers[vnode.context!._uid]
        |                                                         ^
    132 |   keys(handlers).forEach(eventName => {
    133 |     target.removeEventListener(eventName, handlers[eventName])
    134 |   })
ERROR in C:/projects/node_modules/vuetify/src/directives/touch.ts
133:32 Argument of type 'string | number | symbol' is not assignable to parameter of type 'string'.
  Type 'number' is not assignable to type 'string'.
    131 |   const handlers = target._touchHandlers[vnode.context!._uid]
    132 |   keys(handlers).forEach(eventName => {
  > 133 |     target.removeEventListener(eventName, handlers[eventName])
        |                                ^
    134 |   })
    135 |   delete target._touchHandlers[vnode.context!._uid]
    136 | }
ERROR in C:/projects/node_modules/vuetify/src/directives/touch.ts
135:17 Property '_touchHandlers' does not exist on type 'HTMLElement'.
    133 |     target.removeEventListener(eventName, handlers[eventName])
    134 |   })
  > 135 |   delete target._touchHandlers[vnode.context!._uid]
        |                 ^
    136 | }
    137 | 
    138 | export default {
ERROR in C:/projects/node_modules/vuetify/src/directives/touch.ts
135:47 Property '_uid' does not exist on type 'Vue'.
    133 |     target.removeEventListener(eventName, handlers[eventName])
    134 |   })
  > 135 |   delete target._touchHandlers[vnode.context!._uid]
        |                                               ^
    136 | }
    137 | 
    138 | export default {
ERROR in C:/projects/node_modules/vuetify/src/mixins/bootable.ts
16:16 Expected 0-1 arguments, but got 0.
    14 |  */
    15 | /* @vue/component */
  > 16 | export default Vue.extend<Vue & Toggleable>().extend({
       |                ^
    17 |   name: 'bootable',
    18 | 
    19 |   props: {
ERROR in C:/projects/node_modules/vuetify/src/mixins/bootable.ts
29:19 Property 'isBooted' does not exist on type '{ hasContent(): boolean | undefined; }'.
    27 |   computed: {
    28 |     hasContent (): boolean | undefined {
  > 29 |       return this.isBooted || !this.lazy || this.isActive
       |                   ^
    30 |     }
    31 |   },
    32 | 
ERROR in C:/projects/node_modules/vuetify/src/mixins/bootable.ts
29:37 Property 'lazy' does not exist on type '{ hasContent(): boolean | undefined; }'.
    27 |   computed: {
    28 |     hasContent (): boolean | undefined {
  > 29 |       return this.isBooted || !this.lazy || this.isActive
       |                                     ^
    30 |     }
    31 |   },
    32 | 
ERROR in C:/projects/node_modules/vuetify/src/mixins/bootable.ts
29:50 Property 'isActive' does not exist on type '{ hasContent(): boolean | undefined; }'.
    27 |   computed: {
    28 |     hasContent (): boolean | undefined {
  > 29 |       return this.isBooted || !this.lazy || this.isActive
       |                                                  ^
    30 |     }
    31 |   },
    32 | 
ERROR in C:/projects/node_modules/vuetify/src/mixins/bootable.ts
35:12 Property 'isBooted' does not exist on type '{ isActive(): void; }'.
    33 |   watch: {
    34 |     isActive () {
  > 35 |       this.isBooted = true
       |            ^
    36 |     }
    37 |   },
    38 | 
ERROR in C:/projects/node_modules/vuetify/src/mixins/bootable.ts
41:19 Property 'hasContent' does not exist on type '{ showLazyContent(content: VNode[]): VNode[] | undefined; }'.
    39 |   methods: {
    40 |     showLazyContent (content: VNode[]): VNode[] | undefined {
  > 41 |       return this.hasContent ? content : undefined
       |                   ^
    42 |     }
    43 |   }
    44 | })
ERROR in C:/projects/node_modules/vuetify/src/mixins/proxyable.ts
5:22 Cannot find name 'unknown'.
    3 | /* eslint-disable-next-line no-use-before-define */
    4 | export type Proxyable<T extends string = 'value'> = VueConstructor<Vue & {
  > 5 |   internalLazyValue: unknown
      |                      ^
    6 |   internalValue: unknown
    7 | } & Record<T, any>>
    8 | 
ERROR in C:/projects/node_modules/vuetify/src/mixins/proxyable.ts
6:18 Cannot find name 'unknown'.
    4 | export type Proxyable<T extends string = 'value'> = VueConstructor<Vue & {
    5 |   internalLazyValue: unknown
  > 6 |   internalValue: unknown
      |                  ^
    7 | } & Record<T, any>>
    8 | 
    9 | export function factory<T extends string = 'value'> (prop?: T, event?: string): Proxyable<T>
ERROR in C:/projects/node_modules/vuetify/src/mixins/proxyable.ts
30:42 Cannot find name 'unknown'.
    28 |     data () {
    29 |       return {
  > 30 |         internalLazyValue: this[prop] as unknown
       |                                          ^
    31 |       }
    32 |     },
    33 | 
ERROR in C:/projects/node_modules/vuetify/src/mixins/proxyable.ts
36:17 Cannot find name 'unknown'.
    34 |     computed: {
    35 |       internalValue: {
  > 36 |         get (): unknown {
       |                 ^
    37 |           return this.internalLazyValue
    38 |         },
    39 |         set (val: any) {
ERROR in C:/projects/node_modules/vuetify/src/mixins/themeable.ts
21:19 Expected 0-1 arguments, but got 0.
    19 | 
    20 | /* @vue/component */
  > 21 | const Themeable = Vue.extend<Themeable>().extend({
       |                   ^
    22 |   name: 'themeable',
    23 | 
    24 |   provide (): object {
ERROR in C:/projects/node_modules/vuetify/src/mixins/themeable.ts
59:16 Property 'dark' does not exist on type '{ isDark(): boolean; themeClasses(): object; rootIsDark(): boolean; rootThemeClasses(): any; }'.
    57 |   computed: {
    58 |     isDark (): boolean {
  > 59 |       if (this.dark === true) {
       |                ^
    60 |         // explicitly dark
    61 |         return true
    62 |       } else if (this.light === true) {
ERROR in C:/projects/node_modules/vuetify/src/mixins/themeable.ts
62:23 Property 'light' does not exist on type '{ isDark(): boolean; themeClasses(): object; rootIsDark(): boolean; rootThemeClasses(): any; }'.
    60 |         // explicitly dark
    61 |         return true
  > 62 |       } else if (this.light === true) {
       |                       ^
    63 |         // explicitly light
    64 |         return false
    65 |       } else {
ERROR in C:/projects/node_modules/vuetify/src/mixins/themeable.ts
67:21 Property 'theme' does not exist on type '{ isDark(): boolean; themeClasses(): object; rootIsDark(): boolean; rootThemeClasses(): any; }'.
    65 |       } else {
    66 |         // inherit from parent, or default false if there is none
  > 67 |         return this.theme.isDark
       |                     ^
    68 |       }
    69 |     },
    70 |     themeClasses (): object {
ERROR in C:/projects/node_modules/vuetify/src/mixins/themeable.ts
78:16 Property 'dark' does not exist on type '{ isDark(): boolean; themeClasses(): object; rootIsDark(): boolean; rootThemeClasses(): any; }'.
    76 |     /** Used by menus and dialogs, inherits from v-app instead of the parent */
    77 |     rootIsDark (): boolean {
  > 78 |       if (this.dark === true) {
       |                ^
    79 |         // explicitly dark
    80 |         return true
    81 |       } else if (this.light === true) {
ERROR in C:/projects/node_modules/vuetify/src/mixins/themeable.ts
81:23 Property 'light' does not exist on type '{ isDark(): boolean; themeClasses(): object; rootIsDark(): boolean; rootThemeClasses(): any; }'.
    79 |         // explicitly dark
    80 |         return true
  > 81 |       } else if (this.light === true) {
       |                       ^
    82 |         // explicitly light
    83 |         return false
    84 |       } else {
ERROR in C:/projects/node_modules/vuetify/src/mixins/themeable.ts
86:21 Property '$vuetify' does not exist on type '{ isDark(): boolean; themeClasses(): object; rootIsDark(): boolean; rootThemeClasses(): any; }'.
    84 |       } else {
    85 |         // inherit from v-app
  > 86 |         return this.$vuetify.dark
       |                     ^
    87 |       }
    88 |     },
    89 |     rootThemeClasses (): Dictionary<boolean> {
ERROR in C:/projects/node_modules/vuetify/src/mixins/themeable.ts
89:26 Cannot find name 'Dictionary'.
    87 |       }
    88 |     },
  > 89 |     rootThemeClasses (): Dictionary<boolean> {
       |                          ^
    90 |       return {
    91 |         'theme--dark': this.rootIsDark,
    92 |         'theme--light': !this.rootIsDark
ERROR in C:/projects/node_modules/vuetify/src/mixins/themeable.ts
99:16 Parameter 'newVal' implicitly has an 'any' type.
     97 |   watch: {
     98 |     isDark: {
  >  99 |       handler (newVal, oldVal) {
        |                ^
    100 |         if (newVal !== oldVal) {
    101 |           this.themeableProvide.isDark = this.isDark
    102 |         }
ERROR in C:/projects/node_modules/vuetify/src/mixins/themeable.ts
99:24 Parameter 'oldVal' implicitly has an 'any' type.
     97 |   watch: {
     98 |     isDark: {
  >  99 |       handler (newVal, oldVal) {
        |                        ^
    100 |         if (newVal !== oldVal) {
    101 |           this.themeableProvide.isDark = this.isDark
    102 |         }
ERROR in C:/projects/node_modules/vuetify/src/mixins/themeable.ts
101:16 Property 'themeableProvide' does not exist on type '{ handler(newVal: any, oldVal: any): void; immediate: boolean; }'.
     99 |       handler (newVal, oldVal) {
    100 |         if (newVal !== oldVal) {
  > 101 |           this.themeableProvide.isDark = this.isDark
        |                ^
    102 |         }
    103 |       },
    104 |       immediate: true
ERROR in C:/projects/node_modules/vuetify/src/mixins/themeable.ts
101:47 Property 'isDark' does not exist on type '{ handler(newVal: any, oldVal: any): void; immediate: boolean; }'.
     99 |       handler (newVal, oldVal) {
    100 |         if (newVal !== oldVal) {
  > 101 |           this.themeableProvide.isDark = this.isDark
        |                                               ^
    102 |         }
    103 |       },
    104 |       immediate: true
ERROR in C:/projects/node_modules/vuetify/src/util/helpers.ts
259:35 Property 'options' does not exist on type 'VueConstructor<Vue>'.
    257 |   return array.filter(child => {
    258 |     return child.componentOptions &&
  > 259 |       child.componentOptions.Ctor.options.name === tag
        |                                   ^
    260 |   })
    261 | }
    262 | 
ERROR in C:/projects/node_modules/vuetify/src/util/mixins.ts
4:61 A rest parameter must be of an array type.
    2 | import Vue, { VueConstructor } from 'vue'
    3 | 
  > 4 | export default function mixins<T extends VueConstructor[]> (...args: T): ExtractVue<T> extends infer V ? V extends Vue ? VueConstructor<V> : never : never
      |                                                             ^
    5 | export default function mixins<T extends Vue> (...args: VueConstructor[]): VueConstructor<T>
    6 | export default function mixins (...args: VueConstructor[]): VueConstructor {
    7 |   return Vue.extend({ mixins: args })
```

**Comment by ennetech** [comment]
Digging through the code i have found the culprit and managed to hack a solution

```
<script lang="ts">
  import {Component, Vue} from 'vue-property-decorator'
+  import VWindow from '#/vuetify/es5/components/VWindow/VWindow.js'
-   import VWindow from '#/vuetify/src/components/VWindow/VWindow.ts'
  @Component({
    name: 'Window',
    extends: VWindow,
  })
  export default class Window extends Vue {

  }
</script>
```

I have a particular use case in which i need to re-export the components

**Comment by KaelWD** [comment]
That isn't a hack, you shouldn't be importing from src. If you want to import a specific component it should be `import { VWindow } from 'vuetify/lib'`

**Comment by ennetech** [comment]
oh, thank you for the hint!
