### ISSUE TITLE
invalid typing for vuetify

### ISSUE THREAD

**Issue by MichalMeszaros** [vuetifyjs/vuetify#14182]
Configuration:
"vite": "^2.5.10",
"@vuetify/vite-plugin": "1.0.0-alpha.4",
"vuetify": "3.0.0-alpha.11"

my index.ts for vuetify plugin
import 'vuetify/styles';
import { createVuetify } from 'vuetify';

const vuetifyInstance = createVuetify();

During build i get error:

```
src/plugins/vuetify/index.ts:3:10 - error TS2614: Module '"vuetify"' has no exported member 'createVuetify'. Did you mean to use 'import createVuetify from "vuetify"' instead?

3 import { createVuetify } from 'vuetify';
```

**Comment by KaelWD** [comment]
No it isn't: https://unpkg.com/browse/vuetify@3.0.0-alpha.11/lib/index.d.ts

This has worked for me and several other people, so there must be some problem with your project or environment.

**Comment by MichalMeszaros** [comment]
ok this can be closed :/ my bad problem was that somehow when i import vuetify using import `{ createVuetify } from 'vuetify';` typing to this file was referenced from different folder than it should. It did reference d.ts file from the vuetify2
