### ISSUE TITLE
[Bug Report] Date picker with range property not working on Vuetify and Nuxt 2.0 

### ISSUE THREAD

**Issue by mauroalejandrojm** [vuetifyjs/vuetify#9526]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.5.16
**Browsers:** Chrome 77.0.3865.120
**OS:** Mac OS 10.15.0

### Steps to reproduce
Create a component using NuxtJs am using the following instance:

import '@mdi/font/css/materialdesignicons.css';
import Vue from 'vue';
import Vuetify from 'vuetify';
import 'vuetify/dist/vuetify.min.css';

Vue.use(Vuetify);

const opts = {}
const vuetifyOptions = {}
export default ctx => {
const vuetify = new Vuetify({
  opts,
  vuetifyOptions,
  icons: {
    iconfont: 'mdi',
  },
  theme: {
    dark: false
  }
})
ctx.app.vuetify = vuetify
ctx.$vuetify = vuetify.framework
}

then create a date picker component with the range property.

### Expected Behavior
Work as the codepen example

### Actual Behavior
It throws an TypeError: dateString.split is not a function handling the dates on every possible format. 

### Reproduction Link
<a href="https://codepen.io/mauroalejandrojm/pen/dyyVEop" target="_blank">https://codepen.io/mauroalejandrojm/pen/dyyVEop</a>

### Other comments
The multiple property works perfectly, I've just recreate the behaviour of the range property using the multiple.

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by jacekkarczmarczyk** [comment]
> Expected Behavior
> Work as the codepen example

Hmm, codepen doesn't work for me

**Comment by vysakhvasanth** [comment]
I had the same issue. I update to vuetify 2.1.10, and this issue is resolved.

**Comment by johnleider** [comment]
This is working correctly in the latest version.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by jasonuithol** [comment]
I have a very similar issue.  Plain and simple, range is broken.

https://codepen.io/jasonuithol/pen/eYNZYBp?editors=1111

**Comment by jasonuithol** [comment]
vue 2.6.11
    vuetify 2.2.11

**Comment by akhoury** [comment]
this should be re-opened

**Comment by jacekkarczmarczyk** [comment]
@akhoury you're missing `mutliple` prop on date picker

**Comment by akhoury** [comment]
@jacekkarczmarczyk whoops! It was `range` the prop I forgot, but yea, same effect. Thanks
