### ISSUE TITLE
[Bug Report][3.5.2] Duplicate identifier 'ComponentPublicInstance'.

### ISSUE THREAD

**Issue by idefixcert** [vuetifyjs/vuetify#19177]
### Environment
**Vuetify Version:** 3.5.2
**Vue Version:** 3.4.15
**Browsers:** Chrome 121.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
npm install
npm run build

### Expected Behavior
build correct

### Actual Behavior
throws a lot of errors
eg:
node_modules/vuetify/lib/index.d.mts:479:15 - error TS2300: Duplicate identifier 'ComponentPublicInstance'.

### Reproduction Link
[https://github.com/idefixcert/vuetify_error](https://github.com/idefixcert/vuetify_error)

**Comment by heziegl** [comment]
getting the same error(s) after updating from 3.4.11 to 3.5.2:

node_modules/vuetify/lib/index.d.mts:2:29 - error TS2300: Duplicate identifier 'ComponentPublicInstance'.      
2 import { Ref, DeepReadonly, ComponentPublicInstance, JSXComponent, PropType, CSSProperties, App } from 'vue';
                              ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/vuetify/lib/index.d.mts:479:15 - error TS2300: Duplicate identifier 'ComponentPublicInstance'.
479 import type { ComponentPublicInstance, FunctionalComponent, UnwrapNestedRefs, VNodeChild } from 'vue'  
                  ~~~~~~~~~~~~~~~~~~~~~~~

**Comment by zwx00** [comment]
This is very annoying, had this for a while and haven't been able to update vuetify and access the new features :(

**Comment by jacstrong** [comment]
Having the same issue with Vuetify 3.5.1.
