### ISSUE TITLE
[Bug Report][3.3.2] npm run build breaks with v3.3.x

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#17496]
### Environment
**Vuetify Version:** 3.3.2
**Last working version:** 3.2.5
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
'npm run build' no longer functions properly when using Vuetify v3.3.x  This used to work fine using v3.2.5 and below.  Below shows some sample output I am seeing:

```
error TS2307: Cannot find module 'vuetify/lib/components/index' or its corresponding type declarations.'
import type { VForm } from 'vuetify/lib/components/index';
```

A ticket was open here (https://github.com/vuejs/tsconfig/issues/13), but has been closed as it's not an issue with the tsconfig package (as I originally thought).

FWIW here are my working files with v3.2.5:

tsconfig.json
```
{
  "extends": "@tsconfig/node18/tsconfig.json",
  "compilerOptions": {
    "baseUrl": ".",
    "lib": ["esnext", "DOM"],
    "paths": {
      "@/*": ["./src/*"],
    },
    "types": ["node", "vuetify"],
  },
  "references": [
    {
      "path": "./tsconfig.config.json"
    }
  ]
}
```
tsconfig.config.json
```
{
  "extends": "@tsconfig/node18/tsconfig.json",
  "include": ["vite.config.ts"],
  "compilerOptions": {
    "composite": true,
    "skipLibCheck": true,
    "types": ["node", "vuetify"],
    "paths": {
      "@/*": ["./src/*"],
    }
  }
}
```
package.json (trimmed down to only show relevant packages)
```
"dependencies": {
...
    "vue": "^3.3.4",
    "vuetify": "3.2.5"
},  
"devDependencies": {
    "@tsconfig/node18": "^2.0.1",
    "@types/node": "^18.16.14",
    "@vitejs/plugin-vue": "^4.2.3",
    "@vue/tsconfig": "^0.4.0",
    "typescript": "^5.0.4",
    "vite": "^4.3.8",
    "vite-plugin-vuetify": "^1.0.2",
    "vue-tsc": "^1.6.5"
}
```

### Expected Behavior
When I run 'npm run build' it completes without issue

### Actual Behavior
When I run 'npm run build' with v 3.3.x it barfs with errors about not finding vuetify type declarations

### Reproduction Link
[https://jsfiddle.net/](https://jsfiddle.net/)

**Comment by KaelWD** [comment]
That's never had type declarations

https://vuetifyjs.com/en/getting-started/installation/#exposed-exports

**Comment by UglyHobbitFeet** [comment]
@KaelWD Your recommendation fixed those particular lines, thanks!  However I am still seeing issues with Vuetify v3.3x and slots and don't know if it belongs in this ticket or a new one.    I tried two different ways to expose all slots inside a v-data-table and this no longer works in v3.3.x.  For example:
```
            <!-- Attempt #1-->
            <template v-for="(_, slot) in $slots" #[slot]="slotProps">
                <slot :name="slot" v-bind="slotProps || {}"></slot>
            </template>

            <!-- Attempt #2-->
            <template v-for="(slot, index) of Object.keys($slots)" :key="index" v-slot:[slot]>
                <slot :name="slot"></slot>
            </template>
```
now gives me the following error:

``
Element implicitly has an 'any' type because expression of type 'string | number' can't be used to index type '{ [x: `item.${string}`]: { index: number; item: DataTableItem<any>; columns: InternalDataTableHeader[]; isExpanded: (item: DataTableItem<any>) => boolean; toggleExpand: (item: DataTableItem<...>) => void; isSelected: (items: SelectableItem | SelectableItem[]) => boolean; toggleSelect: (item: SelectableItem) => void;...'.
  No index signature with a parameter of type 'string' was found on type '{ [x: `item.${string}`]: { index: number; item: DataTableItem<any>; columns: InternalDataTableHeader[]; isExpanded: (item: DataTableItem<any>) => boolean; toggleExpand: (item: DataTableItem<...>) => void; isSelected: (items: SelectableItem | SelectableItem[]) => boolean; toggleSelect: (item: SelectableItem) => void;...'.ts(7053)
``

**Comment by KaelWD** [comment]
https://github.com/vuejs/language-tools/issues/3216

**Comment by UglyHobbitFeet** [comment]
@KaelWD Thanks for link and good to know I'm not crazy. Unfortunately neither solution mentioned there worked for me, so I guess I'll have to wait until this gets patched. Thanks!!

**Comment by BessetThomas** [comment]
I made it work using this workaround :

```
<script setup lang="ts">
import { useSlots } from 'vue'
const slots: unknown = useSlots()
</script>

<template>
    <template v-for="(_, name) in slots" #[name]="slotData">
      <slot :name="name" v-bind="slotData || {}" />
    </template>
</template
```
