### ISSUE TITLE
Uncaught TypeError: _vm._c is not a function(…)

### ISSUE THREAD

**Issue by huobaiyu** [vuetifyjs/vuetify#14]
when I run mine project, the following error msg logged in console:

[Vue warn]: Error when rendering component <VApp>: 
Uncaught TypeError: _vm._c is not a function(…)

**Comment by lin-xi** [comment]
i have the same question

**Comment by johnleider** [comment]
Ensure that you are using vue@2.1.6. There were breaking changes from vue@2.1.5 that required the build process be updated. Unfortunately, this new process breaks earlier versions. If you are using vue@2.1.6 and vuetify@0.7.7 and this is still happening, please provide some information on your setup please.

**Comment by huobaiyu** [comment]
It works properly after I updated vue version to 2.1.6. Thanks a lot. But I met another issue about v-radio component. Could you give one example how to using v-for for binding multi options?

**Comment by johnleider** [comment]
It would be helpful if you could post what you were trying to do.

**Comment by huobaiyu** [comment]
the following is code:
<v-radio > option1 </v-radio>
but option1 is not be displayed.

**Comment by johnleider** [comment]
I'm going to close this ticket as the original issue has been resolved. Please submit another ticket for the v-radio bug you are experiencing. Thank you!

**Comment by doug3132** [comment]
hi,  i have de same problem!

TypeError: _vm.loadImg is not a function

**Comment by jacekkarczmarczyk** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.

**Comment by wadeh-b** [comment]
:)
