### ISSUE TITLE
<v-text-field> minimum constrain by method is ignored when exactly 0

### ISSUE THREAD

**Issue by theweaklink** [vuetifyjs/vuetify#899]
### Versions
master

### What is expected ?
`<v-text-field :min="MyFunc()" [...]></v-text-field>` should respect any value returned by `MyFunc()`, including `0`

### What is actually happening ?
When `<v-text-field :min="MyFunc()" [...]></v-text-field>` is bound to a function returning exactly `0`, `0` is ignored and no min is set. Anything else than `0` will work (see Fiddles below).
Note that when no function is used (i-e hardcoded to 0), it works as expected: `<v-text-field min="0" [...]></v-text-field>` ==> works

### Reproduction Link
Fiddles:
* with `min=0` (the problem): https://jsfiddle.net/j5Lqb652
* with `min=1` (no problem): https://jsfiddle.net/7cx25dto
* with `min=-1` (no problem): https://jsfiddle.net/62j5w6sf

**Comment by johnleider** [comment]
I'm not sure I understand the issue. If you have a min of 0, then you have no minimum.

**Comment by theweaklink** [comment]
Well, if we want the minimum to be actually 0?
For instance, the count of an item cannot be negative (i-e only >= 0 )

**Comment by johnleider** [comment]
Valid point.

**Comment by theweaklink** [comment]
Argh! nervemind, should be a string being returned!

```
	PreviousItem: function(i) {
    	return (  i== 0 )? "0" : this.items[i-1].count;
    }
```

**Comment by johnleider** [comment]
Well the field is setup to accept a string or number, I should just typecast it for the dev anyways. Leaving this open.

**Comment by theweaklink** [comment]
Makes sense.

In the meantime, using `return "0"` instead of `return 0` will be an easy workaround.

**Comment by theweaklink** [comment]
so quick!
+1
thanks!

**Comment by lattam** [comment]
Hi, this fix is causing the unit tests to fail

`ERROR LOG: '[Vue warn]: Error in render function: "TypeError: undefined is not a function (evaluating '[undefined, null].includes(this.max)')"`

Could it simply check this.max to undefined and null, like this for example ?

`if (this.max != undefined && this.max != null)`

Thank you, Martin

**Comment by johnleider** [comment]
This is causing vuetify tests to fail or your own?

**Comment by lattam** [comment]
My own test for my application which uses vuetify. It is just simple test which renders component containing <v-text-field>. The error is displayed after upgrading from version 13.0 to 13.1 (and all the newer versions)

**Comment by johnleider** [comment]
Can you show me your test setup? There is no reason that should cause
anything to fail.

**Comment by lattam** [comment]
https://gist.github.com/lattam/de07acdbf45c5e3308863da95a66bceb

It is basic setup after "vue init webpack name" with karma unit tests. In karma.conf.js is only one [line added](https://gist.github.com/lattam/de07acdbf45c5e3308863da95a66bceb#file-karma-conf-js-L18) and in package.json I have these:

```
    "promise-polyfill": "^6.0.2",
    "vue": "^2.3.3",
    "vue-router": "^2.6.0",
    "vuetify": "^0.14.7",
    "vuex": "^2.3.1"
```

Works fine for vuetify 0.13.0 but giving me error on newer versions. Thank you for help.
